### ISSUE TITLE
Merge mining abandoned?

### ISSUE THREAD

**Issue by p3yot3** [Emercoin/emercoin#14]
Merge mining was announced over a month ago, but since then - nothing. Has it been abandoned?

**Comment by p3yot3** [comment]
Or is nobody active on this project at all?

**Comment by p3yot3** [comment]
I take it the lack of response here means it is abandoned them.

Thanks for the info.

**Comment by vx28643** [comment]
I am also eager for any news about it. I believe they are still planning to implement merge mining but I don't know for sure (there has been no news to the contrary).

You asked your question only a few days ago, perhaps it has been missed, or does not fit into github issues. You could also ask the question on the Emercoin thread at the bitcointalk.org forum.

regards.

**Comment by EvgenijM86** [comment]
I am doing checkpoints right now. When I am sure that they work correctly I might start adding merged mining.

**Comment by AndreyNag** [comment]
Hi. Any news?

**Comment by EvgenijM86** [comment]
I am working on it currently. It will be in our next release.

**Comment by AndreyNag** [comment]
На сколько далеки перспективы внедрения объединённого майнинга?
Спасибо! ;-)

**Comment by SomeNewGuy** [comment]
I'm now curious as well now if it has been abandoned. I will stop watching the project soon. When devs are unreliable and don't tell the truth about deadlines or intentions it really takes away from any value the coin has whatsoever.

Been more than "the next release" since this was posted. Hope it's not true but it really seems it's turning out to be another shitcoin. Good luck. :)

**Comment by vx28643** [comment]
Emercoin have been regularly adding new features. At the end of September they had a [major new release](http://emercoin.com/2016-09-24-Emercoin_0.5.0_Release_Notes) by updating the GUI to that of Bitcoin 0.10.2 as well as adding many other new features.

Converting to merge mining would be quite a large job and if they changed their mind about this plan then I expect @EvgenijM86 will let us know.

**Comment by p3yot3** [comment]
I doubt it will ever happen - the merge mining press release was just an attention grabbing excersise. I stopped watching this coin as soon as I found out it was run by the same guys who scammed/robbed 100's of crypto enthusiasts trading as Hashcoins. Check out the Hashcoins bitcointalk thread:

https://bitcointalk.org/index.php?topic=417623.840

Emercoin even advertise hashcoins on their website & claim to be partners with them, but in reality they are the same people still doing the same old scam. If you value your crypto you'd do well to avoid this scam outfit - emercoin = hashcoins = scam.

**Comment by maxihatop** [comment]
Thank you. Your opinion is taken into consideration.

**Comment by SomeNewGuy** [comment]
@vx28643 I don't expect you to understand because it's clear your programming ability from that statement about how difficult it would be to implement. Many coins have done it in a short time without many devs at all let alone qualified ones. 

Then there are coins without many devs who on top of that have done it for multi algos. So it should have been well within the scope of possibilities for the devs here. These answers have given me my answer though. A coin where you cant trust the developers or the announcements they make don't offer much. Just another hyped shitcoin.

**Comment by EvgenijM86** [comment]
We have uploaded merged-mining branch to github. Will test it in our testnet. Once we are sure that there are no bugs we will release it.

**Comment by AndreyNag** [comment]
Tell me please. Did you test on big network? Or it is only test?

**Comment by EvgenijM86** [comment]
I did not test on large network. I created 2 private testnets (isolated from the internet) for bitcoin and emercoin and started mining aux pow blocks. So far mining seems to work.

We will do larger scale tests (inside emercoin testnet) this and next week.

And please note: code forbids generation of auxpow block unless 95% of last 1000 blocks were mined by new client. This is called "soft-fork" - it happens only when most people have upgraded. You can disable this in ContextualCheckBlockHeader() function.

**Comment by EvgenijM86** [comment]
Currently our official client (0.5.2.1) will reject merged mining blocks because it has no knowledge of how to handle them, so we cannot test it in our main chain. That is why we are using testnet were we can simulate a soft-fork situation.

**Comment by snvakula** [comment]
Released in v0.6.0

**Comment by AndreyNag** [comment]
Hello. What soft do you recommend for the pool? And what recomendation for pool setup?
I had the sad experience of the use of incompatible software pool and wallet.
Thank you for your attention.
